#
# .travis.yml
#
# Copyright (c) 2019 Junpei Kawamoto
#
# This software is released under the MIT License.
#
# http://opensource.org/licenses/mit-license.php
#
language: go
go:
  - 1.x
script:
  - go test -v ./...
