// Code generated by go-swagger; DO NOT EDIT.

package daemon

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/jkawamoto/go-sia/models"
)

// PostDaemonUpdateReader is a Reader for the PostDaemonUpdate structure.
type PostDaemonUpdateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostDaemonUpdateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewPostDaemonUpdateNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewPostDaemonUpdateDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPostDaemonUpdateNoContent creates a PostDaemonUpdateNoContent with default headers values
func NewPostDaemonUpdateNoContent() *PostDaemonUpdateNoContent {
	return &PostDaemonUpdateNoContent{}
}

/*PostDaemonUpdateNoContent handles this case with default header values.

Successful Response
*/
type PostDaemonUpdateNoContent struct {
}

func (o *PostDaemonUpdateNoContent) Error() string {
	return fmt.Sprintf("[POST /daemon/update][%d] postDaemonUpdateNoContent ", 204)
}

func (o *PostDaemonUpdateNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostDaemonUpdateDefault creates a PostDaemonUpdateDefault with default headers values
func NewPostDaemonUpdateDefault(code int) *PostDaemonUpdateDefault {
	return &PostDaemonUpdateDefault{
		_statusCode: code,
	}
}

/*PostDaemonUpdateDefault handles this case with default header values.

Error Response
*/
type PostDaemonUpdateDefault struct {
	_statusCode int

	Payload *models.StandardError
}

// Code gets the status code for the post daemon update default response
func (o *PostDaemonUpdateDefault) Code() int {
	return o._statusCode
}

func (o *PostDaemonUpdateDefault) Error() string {
	return fmt.Sprintf("[POST /daemon/update][%d] PostDaemonUpdate default  %+v", o._statusCode, o.Payload)
}

func (o *PostDaemonUpdateDefault) GetPayload() *models.StandardError {
	return o.Payload
}

func (o *PostDaemonUpdateDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StandardError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
