// Code generated by go-swagger; DO NOT EDIT.

package daemon

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPostDaemonUpdateParams creates a new PostDaemonUpdateParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostDaemonUpdateParams() *PostDaemonUpdateParams {
	return &PostDaemonUpdateParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostDaemonUpdateParamsWithTimeout creates a new PostDaemonUpdateParams object
// with the ability to set a timeout on a request.
func NewPostDaemonUpdateParamsWithTimeout(timeout time.Duration) *PostDaemonUpdateParams {
	return &PostDaemonUpdateParams{
		timeout: timeout,
	}
}

// NewPostDaemonUpdateParamsWithContext creates a new PostDaemonUpdateParams object
// with the ability to set a context for a request.
func NewPostDaemonUpdateParamsWithContext(ctx context.Context) *PostDaemonUpdateParams {
	return &PostDaemonUpdateParams{
		Context: ctx,
	}
}

// NewPostDaemonUpdateParamsWithHTTPClient creates a new PostDaemonUpdateParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostDaemonUpdateParamsWithHTTPClient(client *http.Client) *PostDaemonUpdateParams {
	return &PostDaemonUpdateParams{
		HTTPClient: client,
	}
}

/* PostDaemonUpdateParams contains all the parameters to send to the API endpoint
   for the post daemon update operation.

   Typically these are written to a http.Request.
*/
type PostDaemonUpdateParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post daemon update params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostDaemonUpdateParams) WithDefaults() *PostDaemonUpdateParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post daemon update params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostDaemonUpdateParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post daemon update params
func (o *PostDaemonUpdateParams) WithTimeout(timeout time.Duration) *PostDaemonUpdateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post daemon update params
func (o *PostDaemonUpdateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post daemon update params
func (o *PostDaemonUpdateParams) WithContext(ctx context.Context) *PostDaemonUpdateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post daemon update params
func (o *PostDaemonUpdateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post daemon update params
func (o *PostDaemonUpdateParams) WithHTTPClient(client *http.Client) *PostDaemonUpdateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post daemon update params
func (o *PostDaemonUpdateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *PostDaemonUpdateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
