// Code generated by go-swagger; DO NOT EDIT.

package renter

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetRenterStreamSiapathParams creates a new GetRenterStreamSiapathParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetRenterStreamSiapathParams() *GetRenterStreamSiapathParams {
	return &GetRenterStreamSiapathParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetRenterStreamSiapathParamsWithTimeout creates a new GetRenterStreamSiapathParams object
// with the ability to set a timeout on a request.
func NewGetRenterStreamSiapathParamsWithTimeout(timeout time.Duration) *GetRenterStreamSiapathParams {
	return &GetRenterStreamSiapathParams{
		timeout: timeout,
	}
}

// NewGetRenterStreamSiapathParamsWithContext creates a new GetRenterStreamSiapathParams object
// with the ability to set a context for a request.
func NewGetRenterStreamSiapathParamsWithContext(ctx context.Context) *GetRenterStreamSiapathParams {
	return &GetRenterStreamSiapathParams{
		Context: ctx,
	}
}

// NewGetRenterStreamSiapathParamsWithHTTPClient creates a new GetRenterStreamSiapathParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetRenterStreamSiapathParamsWithHTTPClient(client *http.Client) *GetRenterStreamSiapathParams {
	return &GetRenterStreamSiapathParams{
		HTTPClient: client,
	}
}

/* GetRenterStreamSiapathParams contains all the parameters to send to the API endpoint
   for the get renter stream siapath operation.

   Typically these are written to a http.Request.
*/
type GetRenterStreamSiapathParams struct {

	// Siapath.
	Siapath string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get renter stream siapath params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetRenterStreamSiapathParams) WithDefaults() *GetRenterStreamSiapathParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get renter stream siapath params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetRenterStreamSiapathParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get renter stream siapath params
func (o *GetRenterStreamSiapathParams) WithTimeout(timeout time.Duration) *GetRenterStreamSiapathParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get renter stream siapath params
func (o *GetRenterStreamSiapathParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get renter stream siapath params
func (o *GetRenterStreamSiapathParams) WithContext(ctx context.Context) *GetRenterStreamSiapathParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get renter stream siapath params
func (o *GetRenterStreamSiapathParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get renter stream siapath params
func (o *GetRenterStreamSiapathParams) WithHTTPClient(client *http.Client) *GetRenterStreamSiapathParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get renter stream siapath params
func (o *GetRenterStreamSiapathParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithSiapath adds the siapath to the get renter stream siapath params
func (o *GetRenterStreamSiapathParams) WithSiapath(siapath string) *GetRenterStreamSiapathParams {
	o.SetSiapath(siapath)
	return o
}

// SetSiapath adds the siapath to the get renter stream siapath params
func (o *GetRenterStreamSiapathParams) SetSiapath(siapath string) {
	o.Siapath = siapath
}

// WriteToRequest writes these params to a swagger request
func (o *GetRenterStreamSiapathParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param siapath
	if err := r.SetPathParam("siapath", o.Siapath); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
