// Code generated by go-swagger; DO NOT EDIT.

package renter

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetRenterBackupParams creates a new GetRenterBackupParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetRenterBackupParams() *GetRenterBackupParams {
	return &GetRenterBackupParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetRenterBackupParamsWithTimeout creates a new GetRenterBackupParams object
// with the ability to set a timeout on a request.
func NewGetRenterBackupParamsWithTimeout(timeout time.Duration) *GetRenterBackupParams {
	return &GetRenterBackupParams{
		timeout: timeout,
	}
}

// NewGetRenterBackupParamsWithContext creates a new GetRenterBackupParams object
// with the ability to set a context for a request.
func NewGetRenterBackupParamsWithContext(ctx context.Context) *GetRenterBackupParams {
	return &GetRenterBackupParams{
		Context: ctx,
	}
}

// NewGetRenterBackupParamsWithHTTPClient creates a new GetRenterBackupParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetRenterBackupParamsWithHTTPClient(client *http.Client) *GetRenterBackupParams {
	return &GetRenterBackupParams{
		HTTPClient: client,
	}
}

/* GetRenterBackupParams contains all the parameters to send to the API endpoint
   for the get renter backup operation.

   Typically these are written to a http.Request.
*/
type GetRenterBackupParams struct {

	/* Host.

	   if requested, fetch the backups stored on a specific host
	*/
	Host *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get renter backup params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetRenterBackupParams) WithDefaults() *GetRenterBackupParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get renter backup params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetRenterBackupParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get renter backup params
func (o *GetRenterBackupParams) WithTimeout(timeout time.Duration) *GetRenterBackupParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get renter backup params
func (o *GetRenterBackupParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get renter backup params
func (o *GetRenterBackupParams) WithContext(ctx context.Context) *GetRenterBackupParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get renter backup params
func (o *GetRenterBackupParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get renter backup params
func (o *GetRenterBackupParams) WithHTTPClient(client *http.Client) *GetRenterBackupParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get renter backup params
func (o *GetRenterBackupParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithHost adds the host to the get renter backup params
func (o *GetRenterBackupParams) WithHost(host *string) *GetRenterBackupParams {
	o.SetHost(host)
	return o
}

// SetHost adds the host to the get renter backup params
func (o *GetRenterBackupParams) SetHost(host *string) {
	o.Host = host
}

// WriteToRequest writes these params to a swagger request
func (o *GetRenterBackupParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Host != nil {

		// query param host
		var qrHost string

		if o.Host != nil {
			qrHost = *o.Host
		}
		qHost := qrHost
		if qHost != "" {

			if err := r.SetQueryParam("host", qHost); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
