// Code generated by go-swagger; DO NOT EDIT.

package renter

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetRenterFilesParams creates a new GetRenterFilesParams object
// with the default values initialized.
func NewGetRenterFilesParams() *GetRenterFilesParams {

	return &GetRenterFilesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetRenterFilesParamsWithTimeout creates a new GetRenterFilesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetRenterFilesParamsWithTimeout(timeout time.Duration) *GetRenterFilesParams {

	return &GetRenterFilesParams{

		timeout: timeout,
	}
}

// NewGetRenterFilesParamsWithContext creates a new GetRenterFilesParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetRenterFilesParamsWithContext(ctx context.Context) *GetRenterFilesParams {

	return &GetRenterFilesParams{

		Context: ctx,
	}
}

// NewGetRenterFilesParamsWithHTTPClient creates a new GetRenterFilesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetRenterFilesParamsWithHTTPClient(client *http.Client) *GetRenterFilesParams {

	return &GetRenterFilesParams{
		HTTPClient: client,
	}
}

/*GetRenterFilesParams contains all the parameters to send to the API endpoint
for the get renter files operation typically these are written to a http.Request
*/
type GetRenterFilesParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get renter files params
func (o *GetRenterFilesParams) WithTimeout(timeout time.Duration) *GetRenterFilesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get renter files params
func (o *GetRenterFilesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get renter files params
func (o *GetRenterFilesParams) WithContext(ctx context.Context) *GetRenterFilesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get renter files params
func (o *GetRenterFilesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get renter files params
func (o *GetRenterFilesParams) WithHTTPClient(client *http.Client) *GetRenterFilesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get renter files params
func (o *GetRenterFilesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetRenterFilesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
