// Code generated by go-swagger; DO NOT EDIT.

package renter

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetRenterContractsParams creates a new GetRenterContractsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetRenterContractsParams() *GetRenterContractsParams {
	return &GetRenterContractsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetRenterContractsParamsWithTimeout creates a new GetRenterContractsParams object
// with the ability to set a timeout on a request.
func NewGetRenterContractsParamsWithTimeout(timeout time.Duration) *GetRenterContractsParams {
	return &GetRenterContractsParams{
		timeout: timeout,
	}
}

// NewGetRenterContractsParamsWithContext creates a new GetRenterContractsParams object
// with the ability to set a context for a request.
func NewGetRenterContractsParamsWithContext(ctx context.Context) *GetRenterContractsParams {
	return &GetRenterContractsParams{
		Context: ctx,
	}
}

// NewGetRenterContractsParamsWithHTTPClient creates a new GetRenterContractsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetRenterContractsParamsWithHTTPClient(client *http.Client) *GetRenterContractsParams {
	return &GetRenterContractsParams{
		HTTPClient: client,
	}
}

/* GetRenterContractsParams contains all the parameters to send to the API endpoint
   for the get renter contracts operation.

   Typically these are written to a http.Request.
*/
type GetRenterContractsParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get renter contracts params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetRenterContractsParams) WithDefaults() *GetRenterContractsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get renter contracts params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetRenterContractsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get renter contracts params
func (o *GetRenterContractsParams) WithTimeout(timeout time.Duration) *GetRenterContractsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get renter contracts params
func (o *GetRenterContractsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get renter contracts params
func (o *GetRenterContractsParams) WithContext(ctx context.Context) *GetRenterContractsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get renter contracts params
func (o *GetRenterContractsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get renter contracts params
func (o *GetRenterContractsParams) WithHTTPClient(client *http.Client) *GetRenterContractsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get renter contracts params
func (o *GetRenterContractsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetRenterContractsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
