// Code generated by go-swagger; DO NOT EDIT.

package renter

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPostRenterDeleteSiapathParams creates a new PostRenterDeleteSiapathParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostRenterDeleteSiapathParams() *PostRenterDeleteSiapathParams {
	return &PostRenterDeleteSiapathParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostRenterDeleteSiapathParamsWithTimeout creates a new PostRenterDeleteSiapathParams object
// with the ability to set a timeout on a request.
func NewPostRenterDeleteSiapathParamsWithTimeout(timeout time.Duration) *PostRenterDeleteSiapathParams {
	return &PostRenterDeleteSiapathParams{
		timeout: timeout,
	}
}

// NewPostRenterDeleteSiapathParamsWithContext creates a new PostRenterDeleteSiapathParams object
// with the ability to set a context for a request.
func NewPostRenterDeleteSiapathParamsWithContext(ctx context.Context) *PostRenterDeleteSiapathParams {
	return &PostRenterDeleteSiapathParams{
		Context: ctx,
	}
}

// NewPostRenterDeleteSiapathParamsWithHTTPClient creates a new PostRenterDeleteSiapathParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostRenterDeleteSiapathParamsWithHTTPClient(client *http.Client) *PostRenterDeleteSiapathParams {
	return &PostRenterDeleteSiapathParams{
		HTTPClient: client,
	}
}

/* PostRenterDeleteSiapathParams contains all the parameters to send to the API endpoint
   for the post renter delete siapath operation.

   Typically these are written to a http.Request.
*/
type PostRenterDeleteSiapathParams struct {

	/* Siapath.

	   Location of the file in the renter on the network.
	*/
	Siapath string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post renter delete siapath params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostRenterDeleteSiapathParams) WithDefaults() *PostRenterDeleteSiapathParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post renter delete siapath params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostRenterDeleteSiapathParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post renter delete siapath params
func (o *PostRenterDeleteSiapathParams) WithTimeout(timeout time.Duration) *PostRenterDeleteSiapathParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post renter delete siapath params
func (o *PostRenterDeleteSiapathParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post renter delete siapath params
func (o *PostRenterDeleteSiapathParams) WithContext(ctx context.Context) *PostRenterDeleteSiapathParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post renter delete siapath params
func (o *PostRenterDeleteSiapathParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post renter delete siapath params
func (o *PostRenterDeleteSiapathParams) WithHTTPClient(client *http.Client) *PostRenterDeleteSiapathParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post renter delete siapath params
func (o *PostRenterDeleteSiapathParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithSiapath adds the siapath to the post renter delete siapath params
func (o *PostRenterDeleteSiapathParams) WithSiapath(siapath string) *PostRenterDeleteSiapathParams {
	o.SetSiapath(siapath)
	return o
}

// SetSiapath adds the siapath to the post renter delete siapath params
func (o *PostRenterDeleteSiapathParams) SetSiapath(siapath string) {
	o.Siapath = siapath
}

// WriteToRequest writes these params to a swagger request
func (o *PostRenterDeleteSiapathParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param siapath
	if err := r.SetPathParam("siapath", o.Siapath); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
