// Code generated by go-swagger; DO NOT EDIT.

package renter

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/jkawamoto/go-sia/models"
)

// PostRenterRenameSiapathReader is a Reader for the PostRenterRenameSiapath structure.
type PostRenterRenameSiapathReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostRenterRenameSiapathReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 204:
		result := NewPostRenterRenameSiapathNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewPostRenterRenameSiapathDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPostRenterRenameSiapathNoContent creates a PostRenterRenameSiapathNoContent with default headers values
func NewPostRenterRenameSiapathNoContent() *PostRenterRenameSiapathNoContent {
	return &PostRenterRenameSiapathNoContent{}
}

/*PostRenterRenameSiapathNoContent handles this case with default header values.

Successful Response
*/
type PostRenterRenameSiapathNoContent struct {
}

func (o *PostRenterRenameSiapathNoContent) Error() string {
	return fmt.Sprintf("[POST /renter/rename/{siapath}][%d] postRenterRenameSiapathNoContent ", 204)
}

func (o *PostRenterRenameSiapathNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostRenterRenameSiapathDefault creates a PostRenterRenameSiapathDefault with default headers values
func NewPostRenterRenameSiapathDefault(code int) *PostRenterRenameSiapathDefault {
	return &PostRenterRenameSiapathDefault{
		_statusCode: code,
	}
}

/*PostRenterRenameSiapathDefault handles this case with default header values.

Error Response
*/
type PostRenterRenameSiapathDefault struct {
	_statusCode int

	Payload *models.StandardError
}

// Code gets the status code for the post renter rename siapath default response
func (o *PostRenterRenameSiapathDefault) Code() int {
	return o._statusCode
}

func (o *PostRenterRenameSiapathDefault) Error() string {
	return fmt.Sprintf("[POST /renter/rename/{siapath}][%d] PostRenterRenameSiapath default  %+v", o._statusCode, o.Payload)
}

func (o *PostRenterRenameSiapathDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StandardError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
