// Code generated by go-swagger; DO NOT EDIT.

package renter

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/jkawamoto/go-sia/models"
)

// PostRenterDownloadsClearReader is a Reader for the PostRenterDownloadsClear structure.
type PostRenterDownloadsClearReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostRenterDownloadsClearReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewPostRenterDownloadsClearNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewPostRenterDownloadsClearDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPostRenterDownloadsClearNoContent creates a PostRenterDownloadsClearNoContent with default headers values
func NewPostRenterDownloadsClearNoContent() *PostRenterDownloadsClearNoContent {
	return &PostRenterDownloadsClearNoContent{}
}

/* PostRenterDownloadsClearNoContent describes a response with status code 204, with default header values.

Successful Response
*/
type PostRenterDownloadsClearNoContent struct {
}

func (o *PostRenterDownloadsClearNoContent) Error() string {
	return fmt.Sprintf("[POST /renter/downloads/clear][%d] postRenterDownloadsClearNoContent ", 204)
}

func (o *PostRenterDownloadsClearNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostRenterDownloadsClearDefault creates a PostRenterDownloadsClearDefault with default headers values
func NewPostRenterDownloadsClearDefault(code int) *PostRenterDownloadsClearDefault {
	return &PostRenterDownloadsClearDefault{
		_statusCode: code,
	}
}

/* PostRenterDownloadsClearDefault describes a response with status code -1, with default header values.

Error Response
*/
type PostRenterDownloadsClearDefault struct {
	_statusCode int

	Payload *models.StandardError
}

// Code gets the status code for the post renter downloads clear default response
func (o *PostRenterDownloadsClearDefault) Code() int {
	return o._statusCode
}

func (o *PostRenterDownloadsClearDefault) Error() string {
	return fmt.Sprintf("[POST /renter/downloads/clear][%d] PostRenterDownloadsClear default  %+v", o._statusCode, o.Payload)
}
func (o *PostRenterDownloadsClearDefault) GetPayload() *models.StandardError {
	return o.Payload
}

func (o *PostRenterDownloadsClearDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StandardError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
