// Code generated by go-swagger; DO NOT EDIT.

package renter

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/jkawamoto/go-sia/models"
)

// PostRenterReader is a Reader for the PostRenter structure.
type PostRenterReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostRenterReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 204:
		result := NewPostRenterNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewPostRenterDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPostRenterNoContent creates a PostRenterNoContent with default headers values
func NewPostRenterNoContent() *PostRenterNoContent {
	return &PostRenterNoContent{}
}

/*PostRenterNoContent handles this case with default header values.

Successful Response
*/
type PostRenterNoContent struct {
}

func (o *PostRenterNoContent) Error() string {
	return fmt.Sprintf("[POST /renter][%d] postRenterNoContent ", 204)
}

func (o *PostRenterNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostRenterDefault creates a PostRenterDefault with default headers values
func NewPostRenterDefault(code int) *PostRenterDefault {
	return &PostRenterDefault{
		_statusCode: code,
	}
}

/*PostRenterDefault handles this case with default header values.

Error Response
*/
type PostRenterDefault struct {
	_statusCode int

	Payload *models.StandardError
}

// Code gets the status code for the post renter default response
func (o *PostRenterDefault) Code() int {
	return o._statusCode
}

func (o *PostRenterDefault) Error() string {
	return fmt.Sprintf("[POST /renter][%d] PostRenter default  %+v", o._statusCode, o.Payload)
}

func (o *PostRenterDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StandardError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
