// Code generated by go-swagger; DO NOT EDIT.

package host_d_b

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetHostdbAllParams creates a new GetHostdbAllParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetHostdbAllParams() *GetHostdbAllParams {
	return &GetHostdbAllParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetHostdbAllParamsWithTimeout creates a new GetHostdbAllParams object
// with the ability to set a timeout on a request.
func NewGetHostdbAllParamsWithTimeout(timeout time.Duration) *GetHostdbAllParams {
	return &GetHostdbAllParams{
		timeout: timeout,
	}
}

// NewGetHostdbAllParamsWithContext creates a new GetHostdbAllParams object
// with the ability to set a context for a request.
func NewGetHostdbAllParamsWithContext(ctx context.Context) *GetHostdbAllParams {
	return &GetHostdbAllParams{
		Context: ctx,
	}
}

// NewGetHostdbAllParamsWithHTTPClient creates a new GetHostdbAllParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetHostdbAllParamsWithHTTPClient(client *http.Client) *GetHostdbAllParams {
	return &GetHostdbAllParams{
		HTTPClient: client,
	}
}

/* GetHostdbAllParams contains all the parameters to send to the API endpoint
   for the get hostdb all operation.

   Typically these are written to a http.Request.
*/
type GetHostdbAllParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get hostdb all params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetHostdbAllParams) WithDefaults() *GetHostdbAllParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get hostdb all params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetHostdbAllParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get hostdb all params
func (o *GetHostdbAllParams) WithTimeout(timeout time.Duration) *GetHostdbAllParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get hostdb all params
func (o *GetHostdbAllParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get hostdb all params
func (o *GetHostdbAllParams) WithContext(ctx context.Context) *GetHostdbAllParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get hostdb all params
func (o *GetHostdbAllParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get hostdb all params
func (o *GetHostdbAllParams) WithHTTPClient(client *http.Client) *GetHostdbAllParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get hostdb all params
func (o *GetHostdbAllParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetHostdbAllParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
