// Code generated by go-swagger; DO NOT EDIT.

package host_d_b

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetHostdbFiltermodeParams creates a new GetHostdbFiltermodeParams object
// with the default values initialized.
func NewGetHostdbFiltermodeParams() *GetHostdbFiltermodeParams {

	return &GetHostdbFiltermodeParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetHostdbFiltermodeParamsWithTimeout creates a new GetHostdbFiltermodeParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetHostdbFiltermodeParamsWithTimeout(timeout time.Duration) *GetHostdbFiltermodeParams {

	return &GetHostdbFiltermodeParams{

		timeout: timeout,
	}
}

// NewGetHostdbFiltermodeParamsWithContext creates a new GetHostdbFiltermodeParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetHostdbFiltermodeParamsWithContext(ctx context.Context) *GetHostdbFiltermodeParams {

	return &GetHostdbFiltermodeParams{

		Context: ctx,
	}
}

// NewGetHostdbFiltermodeParamsWithHTTPClient creates a new GetHostdbFiltermodeParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetHostdbFiltermodeParamsWithHTTPClient(client *http.Client) *GetHostdbFiltermodeParams {

	return &GetHostdbFiltermodeParams{
		HTTPClient: client,
	}
}

/*GetHostdbFiltermodeParams contains all the parameters to send to the API endpoint
for the get hostdb filtermode operation typically these are written to a http.Request
*/
type GetHostdbFiltermodeParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get hostdb filtermode params
func (o *GetHostdbFiltermodeParams) WithTimeout(timeout time.Duration) *GetHostdbFiltermodeParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get hostdb filtermode params
func (o *GetHostdbFiltermodeParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get hostdb filtermode params
func (o *GetHostdbFiltermodeParams) WithContext(ctx context.Context) *GetHostdbFiltermodeParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get hostdb filtermode params
func (o *GetHostdbFiltermodeParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get hostdb filtermode params
func (o *GetHostdbFiltermodeParams) WithHTTPClient(client *http.Client) *GetHostdbFiltermodeParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get hostdb filtermode params
func (o *GetHostdbFiltermodeParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetHostdbFiltermodeParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
