// Code generated by go-swagger; DO NOT EDIT.

package gateway

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/jkawamoto/go-sia/models"
)

// PostGatewayDisconnectNetaddressReader is a Reader for the PostGatewayDisconnectNetaddress structure.
type PostGatewayDisconnectNetaddressReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostGatewayDisconnectNetaddressReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 204:
		result := NewPostGatewayDisconnectNetaddressNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewPostGatewayDisconnectNetaddressDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPostGatewayDisconnectNetaddressNoContent creates a PostGatewayDisconnectNetaddressNoContent with default headers values
func NewPostGatewayDisconnectNetaddressNoContent() *PostGatewayDisconnectNetaddressNoContent {
	return &PostGatewayDisconnectNetaddressNoContent{}
}

/*PostGatewayDisconnectNetaddressNoContent handles this case with default header values.

Successful Response
*/
type PostGatewayDisconnectNetaddressNoContent struct {
}

func (o *PostGatewayDisconnectNetaddressNoContent) Error() string {
	return fmt.Sprintf("[POST /gateway/disconnect/{netaddress}][%d] postGatewayDisconnectNetaddressNoContent ", 204)
}

func (o *PostGatewayDisconnectNetaddressNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostGatewayDisconnectNetaddressDefault creates a PostGatewayDisconnectNetaddressDefault with default headers values
func NewPostGatewayDisconnectNetaddressDefault(code int) *PostGatewayDisconnectNetaddressDefault {
	return &PostGatewayDisconnectNetaddressDefault{
		_statusCode: code,
	}
}

/*PostGatewayDisconnectNetaddressDefault handles this case with default header values.

Error Response
*/
type PostGatewayDisconnectNetaddressDefault struct {
	_statusCode int

	Payload *models.StandardError
}

// Code gets the status code for the post gateway disconnect netaddress default response
func (o *PostGatewayDisconnectNetaddressDefault) Code() int {
	return o._statusCode
}

func (o *PostGatewayDisconnectNetaddressDefault) Error() string {
	return fmt.Sprintf("[POST /gateway/disconnect/{netaddress}][%d] PostGatewayDisconnectNetaddress default  %+v", o._statusCode, o.Payload)
}

func (o *PostGatewayDisconnectNetaddressDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StandardError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
