// Code generated by go-swagger; DO NOT EDIT.

package gateway

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/jkawamoto/go-sia/models"
)

// PostGatewayConnectNetaddressReader is a Reader for the PostGatewayConnectNetaddress structure.
type PostGatewayConnectNetaddressReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostGatewayConnectNetaddressReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewPostGatewayConnectNetaddressNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewPostGatewayConnectNetaddressDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPostGatewayConnectNetaddressNoContent creates a PostGatewayConnectNetaddressNoContent with default headers values
func NewPostGatewayConnectNetaddressNoContent() *PostGatewayConnectNetaddressNoContent {
	return &PostGatewayConnectNetaddressNoContent{}
}

/*PostGatewayConnectNetaddressNoContent handles this case with default header values.

Successful Response
*/
type PostGatewayConnectNetaddressNoContent struct {
}

func (o *PostGatewayConnectNetaddressNoContent) Error() string {
	return fmt.Sprintf("[POST /gateway/connect/{netaddress}][%d] postGatewayConnectNetaddressNoContent ", 204)
}

func (o *PostGatewayConnectNetaddressNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostGatewayConnectNetaddressDefault creates a PostGatewayConnectNetaddressDefault with default headers values
func NewPostGatewayConnectNetaddressDefault(code int) *PostGatewayConnectNetaddressDefault {
	return &PostGatewayConnectNetaddressDefault{
		_statusCode: code,
	}
}

/*PostGatewayConnectNetaddressDefault handles this case with default header values.

Error Response
*/
type PostGatewayConnectNetaddressDefault struct {
	_statusCode int

	Payload *models.StandardError
}

// Code gets the status code for the post gateway connect netaddress default response
func (o *PostGatewayConnectNetaddressDefault) Code() int {
	return o._statusCode
}

func (o *PostGatewayConnectNetaddressDefault) Error() string {
	return fmt.Sprintf("[POST /gateway/connect/{netaddress}][%d] PostGatewayConnectNetaddress default  %+v", o._statusCode, o.Payload)
}

func (o *PostGatewayConnectNetaddressDefault) GetPayload() *models.StandardError {
	return o.Payload
}

func (o *PostGatewayConnectNetaddressDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StandardError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
