// Code generated by go-swagger; DO NOT EDIT.

package host

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewPostHostStorageFoldersRemoveParams creates a new PostHostStorageFoldersRemoveParams object
// with the default values initialized.
func NewPostHostStorageFoldersRemoveParams() *PostHostStorageFoldersRemoveParams {
	var ()
	return &PostHostStorageFoldersRemoveParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostHostStorageFoldersRemoveParamsWithTimeout creates a new PostHostStorageFoldersRemoveParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostHostStorageFoldersRemoveParamsWithTimeout(timeout time.Duration) *PostHostStorageFoldersRemoveParams {
	var ()
	return &PostHostStorageFoldersRemoveParams{

		timeout: timeout,
	}
}

// NewPostHostStorageFoldersRemoveParamsWithContext creates a new PostHostStorageFoldersRemoveParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostHostStorageFoldersRemoveParamsWithContext(ctx context.Context) *PostHostStorageFoldersRemoveParams {
	var ()
	return &PostHostStorageFoldersRemoveParams{

		Context: ctx,
	}
}

// NewPostHostStorageFoldersRemoveParamsWithHTTPClient creates a new PostHostStorageFoldersRemoveParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostHostStorageFoldersRemoveParamsWithHTTPClient(client *http.Client) *PostHostStorageFoldersRemoveParams {
	var ()
	return &PostHostStorageFoldersRemoveParams{
		HTTPClient: client,
	}
}

/*PostHostStorageFoldersRemoveParams contains all the parameters to send to the API endpoint
for the post host storage folders remove operation typically these are written to a http.Request
*/
type PostHostStorageFoldersRemoveParams struct {

	/*Force
	  If `force` is true, the storage folder will be removed even if the data in
	the storage folder cannot be moved to other storage folders, typically
	because they don't have sufficient capacity. If `force` is true and the data
	cannot be moved, data will be lost.


	*/
	Force *bool
	/*Path
	  Local path on disk to the storage folder to remove.

	*/
	Path string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post host storage folders remove params
func (o *PostHostStorageFoldersRemoveParams) WithTimeout(timeout time.Duration) *PostHostStorageFoldersRemoveParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post host storage folders remove params
func (o *PostHostStorageFoldersRemoveParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post host storage folders remove params
func (o *PostHostStorageFoldersRemoveParams) WithContext(ctx context.Context) *PostHostStorageFoldersRemoveParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post host storage folders remove params
func (o *PostHostStorageFoldersRemoveParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post host storage folders remove params
func (o *PostHostStorageFoldersRemoveParams) WithHTTPClient(client *http.Client) *PostHostStorageFoldersRemoveParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post host storage folders remove params
func (o *PostHostStorageFoldersRemoveParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithForce adds the force to the post host storage folders remove params
func (o *PostHostStorageFoldersRemoveParams) WithForce(force *bool) *PostHostStorageFoldersRemoveParams {
	o.SetForce(force)
	return o
}

// SetForce adds the force to the post host storage folders remove params
func (o *PostHostStorageFoldersRemoveParams) SetForce(force *bool) {
	o.Force = force
}

// WithPath adds the path to the post host storage folders remove params
func (o *PostHostStorageFoldersRemoveParams) WithPath(path string) *PostHostStorageFoldersRemoveParams {
	o.SetPath(path)
	return o
}

// SetPath adds the path to the post host storage folders remove params
func (o *PostHostStorageFoldersRemoveParams) SetPath(path string) {
	o.Path = path
}

// WriteToRequest writes these params to a swagger request
func (o *PostHostStorageFoldersRemoveParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Force != nil {

		// query param force
		var qrForce bool
		if o.Force != nil {
			qrForce = *o.Force
		}
		qForce := swag.FormatBool(qrForce)
		if qForce != "" {
			if err := r.SetQueryParam("force", qForce); err != nil {
				return err
			}
		}

	}

	// query param path
	qrPath := o.Path
	qPath := qrPath
	if qPath != "" {
		if err := r.SetQueryParam("path", qPath); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
