// Code generated by go-swagger; DO NOT EDIT.

package host

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/jkawamoto/go-sia/models"
)

// PostHostStorageSectorsDeleteMerklerootReader is a Reader for the PostHostStorageSectorsDeleteMerkleroot structure.
type PostHostStorageSectorsDeleteMerklerootReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostHostStorageSectorsDeleteMerklerootReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 204:
		result := NewPostHostStorageSectorsDeleteMerklerootNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewPostHostStorageSectorsDeleteMerklerootDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPostHostStorageSectorsDeleteMerklerootNoContent creates a PostHostStorageSectorsDeleteMerklerootNoContent with default headers values
func NewPostHostStorageSectorsDeleteMerklerootNoContent() *PostHostStorageSectorsDeleteMerklerootNoContent {
	return &PostHostStorageSectorsDeleteMerklerootNoContent{}
}

/*PostHostStorageSectorsDeleteMerklerootNoContent handles this case with default header values.

Successful Response
*/
type PostHostStorageSectorsDeleteMerklerootNoContent struct {
}

func (o *PostHostStorageSectorsDeleteMerklerootNoContent) Error() string {
	return fmt.Sprintf("[POST /host/storage/sectors/delete/{merkleroot}][%d] postHostStorageSectorsDeleteMerklerootNoContent ", 204)
}

func (o *PostHostStorageSectorsDeleteMerklerootNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostHostStorageSectorsDeleteMerklerootDefault creates a PostHostStorageSectorsDeleteMerklerootDefault with default headers values
func NewPostHostStorageSectorsDeleteMerklerootDefault(code int) *PostHostStorageSectorsDeleteMerklerootDefault {
	return &PostHostStorageSectorsDeleteMerklerootDefault{
		_statusCode: code,
	}
}

/*PostHostStorageSectorsDeleteMerklerootDefault handles this case with default header values.

Error Response
*/
type PostHostStorageSectorsDeleteMerklerootDefault struct {
	_statusCode int

	Payload *models.StandardError
}

// Code gets the status code for the post host storage sectors delete merkleroot default response
func (o *PostHostStorageSectorsDeleteMerklerootDefault) Code() int {
	return o._statusCode
}

func (o *PostHostStorageSectorsDeleteMerklerootDefault) Error() string {
	return fmt.Sprintf("[POST /host/storage/sectors/delete/{merkleroot}][%d] PostHostStorageSectorsDeleteMerkleroot default  %+v", o._statusCode, o.Payload)
}

func (o *PostHostStorageSectorsDeleteMerklerootDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StandardError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
