// Code generated by go-swagger; DO NOT EDIT.

package wallet

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetWalletSeedsParams creates a new GetWalletSeedsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetWalletSeedsParams() *GetWalletSeedsParams {
	return &GetWalletSeedsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetWalletSeedsParamsWithTimeout creates a new GetWalletSeedsParams object
// with the ability to set a timeout on a request.
func NewGetWalletSeedsParamsWithTimeout(timeout time.Duration) *GetWalletSeedsParams {
	return &GetWalletSeedsParams{
		timeout: timeout,
	}
}

// NewGetWalletSeedsParamsWithContext creates a new GetWalletSeedsParams object
// with the ability to set a context for a request.
func NewGetWalletSeedsParamsWithContext(ctx context.Context) *GetWalletSeedsParams {
	return &GetWalletSeedsParams{
		Context: ctx,
	}
}

// NewGetWalletSeedsParamsWithHTTPClient creates a new GetWalletSeedsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetWalletSeedsParamsWithHTTPClient(client *http.Client) *GetWalletSeedsParams {
	return &GetWalletSeedsParams{
		HTTPClient: client,
	}
}

/* GetWalletSeedsParams contains all the parameters to send to the API endpoint
   for the get wallet seeds operation.

   Typically these are written to a http.Request.
*/
type GetWalletSeedsParams struct {

	/* Dictionary.

	   Name of the dictionary that should be used when encoding the seed. 'english' is the most common choice when picking a dictionary.
	*/
	Dictionary *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get wallet seeds params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetWalletSeedsParams) WithDefaults() *GetWalletSeedsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get wallet seeds params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetWalletSeedsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get wallet seeds params
func (o *GetWalletSeedsParams) WithTimeout(timeout time.Duration) *GetWalletSeedsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get wallet seeds params
func (o *GetWalletSeedsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get wallet seeds params
func (o *GetWalletSeedsParams) WithContext(ctx context.Context) *GetWalletSeedsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get wallet seeds params
func (o *GetWalletSeedsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get wallet seeds params
func (o *GetWalletSeedsParams) WithHTTPClient(client *http.Client) *GetWalletSeedsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get wallet seeds params
func (o *GetWalletSeedsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDictionary adds the dictionary to the get wallet seeds params
func (o *GetWalletSeedsParams) WithDictionary(dictionary *string) *GetWalletSeedsParams {
	o.SetDictionary(dictionary)
	return o
}

// SetDictionary adds the dictionary to the get wallet seeds params
func (o *GetWalletSeedsParams) SetDictionary(dictionary *string) {
	o.Dictionary = dictionary
}

// WriteToRequest writes these params to a swagger request
func (o *GetWalletSeedsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Dictionary != nil {

		// query param dictionary
		var qrDictionary string

		if o.Dictionary != nil {
			qrDictionary = *o.Dictionary
		}
		qDictionary := qrDictionary
		if qDictionary != "" {

			if err := r.SetQueryParam("dictionary", qDictionary); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
