// Code generated by go-swagger; DO NOT EDIT.

package wallet

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetWalletTransactionIDParams creates a new GetWalletTransactionIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetWalletTransactionIDParams() *GetWalletTransactionIDParams {
	return &GetWalletTransactionIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetWalletTransactionIDParamsWithTimeout creates a new GetWalletTransactionIDParams object
// with the ability to set a timeout on a request.
func NewGetWalletTransactionIDParamsWithTimeout(timeout time.Duration) *GetWalletTransactionIDParams {
	return &GetWalletTransactionIDParams{
		timeout: timeout,
	}
}

// NewGetWalletTransactionIDParamsWithContext creates a new GetWalletTransactionIDParams object
// with the ability to set a context for a request.
func NewGetWalletTransactionIDParamsWithContext(ctx context.Context) *GetWalletTransactionIDParams {
	return &GetWalletTransactionIDParams{
		Context: ctx,
	}
}

// NewGetWalletTransactionIDParamsWithHTTPClient creates a new GetWalletTransactionIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetWalletTransactionIDParamsWithHTTPClient(client *http.Client) *GetWalletTransactionIDParams {
	return &GetWalletTransactionIDParams{
		HTTPClient: client,
	}
}

/* GetWalletTransactionIDParams contains all the parameters to send to the API endpoint
   for the get wallet transaction ID operation.

   Typically these are written to a http.Request.
*/
type GetWalletTransactionIDParams struct {

	/* ID.

	   ID of the transaction being requested.
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get wallet transaction ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetWalletTransactionIDParams) WithDefaults() *GetWalletTransactionIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get wallet transaction ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetWalletTransactionIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get wallet transaction ID params
func (o *GetWalletTransactionIDParams) WithTimeout(timeout time.Duration) *GetWalletTransactionIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get wallet transaction ID params
func (o *GetWalletTransactionIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get wallet transaction ID params
func (o *GetWalletTransactionIDParams) WithContext(ctx context.Context) *GetWalletTransactionIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get wallet transaction ID params
func (o *GetWalletTransactionIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get wallet transaction ID params
func (o *GetWalletTransactionIDParams) WithHTTPClient(client *http.Client) *GetWalletTransactionIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get wallet transaction ID params
func (o *GetWalletTransactionIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get wallet transaction ID params
func (o *GetWalletTransactionIDParams) WithID(id string) *GetWalletTransactionIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get wallet transaction ID params
func (o *GetWalletTransactionIDParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetWalletTransactionIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
