// Code generated by go-swagger; DO NOT EDIT.

package wallet

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetWalletTransactionIDParams creates a new GetWalletTransactionIDParams object
// with the default values initialized.
func NewGetWalletTransactionIDParams() *GetWalletTransactionIDParams {
	var ()
	return &GetWalletTransactionIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetWalletTransactionIDParamsWithTimeout creates a new GetWalletTransactionIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetWalletTransactionIDParamsWithTimeout(timeout time.Duration) *GetWalletTransactionIDParams {
	var ()
	return &GetWalletTransactionIDParams{

		timeout: timeout,
	}
}

// NewGetWalletTransactionIDParamsWithContext creates a new GetWalletTransactionIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetWalletTransactionIDParamsWithContext(ctx context.Context) *GetWalletTransactionIDParams {
	var ()
	return &GetWalletTransactionIDParams{

		Context: ctx,
	}
}

// NewGetWalletTransactionIDParamsWithHTTPClient creates a new GetWalletTransactionIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetWalletTransactionIDParamsWithHTTPClient(client *http.Client) *GetWalletTransactionIDParams {
	var ()
	return &GetWalletTransactionIDParams{
		HTTPClient: client,
	}
}

/*GetWalletTransactionIDParams contains all the parameters to send to the API endpoint
for the get wallet transaction ID operation typically these are written to a http.Request
*/
type GetWalletTransactionIDParams struct {

	/*ID
	  ID of the transaction being requested.

	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get wallet transaction ID params
func (o *GetWalletTransactionIDParams) WithTimeout(timeout time.Duration) *GetWalletTransactionIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get wallet transaction ID params
func (o *GetWalletTransactionIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get wallet transaction ID params
func (o *GetWalletTransactionIDParams) WithContext(ctx context.Context) *GetWalletTransactionIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get wallet transaction ID params
func (o *GetWalletTransactionIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get wallet transaction ID params
func (o *GetWalletTransactionIDParams) WithHTTPClient(client *http.Client) *GetWalletTransactionIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get wallet transaction ID params
func (o *GetWalletTransactionIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get wallet transaction ID params
func (o *GetWalletTransactionIDParams) WithID(id string) *GetWalletTransactionIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get wallet transaction ID params
func (o *GetWalletTransactionIDParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetWalletTransactionIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
