// Code generated by go-swagger; DO NOT EDIT.

package wallet

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetWalletVerifyAddressAddrParams creates a new GetWalletVerifyAddressAddrParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetWalletVerifyAddressAddrParams() *GetWalletVerifyAddressAddrParams {
	return &GetWalletVerifyAddressAddrParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetWalletVerifyAddressAddrParamsWithTimeout creates a new GetWalletVerifyAddressAddrParams object
// with the ability to set a timeout on a request.
func NewGetWalletVerifyAddressAddrParamsWithTimeout(timeout time.Duration) *GetWalletVerifyAddressAddrParams {
	return &GetWalletVerifyAddressAddrParams{
		timeout: timeout,
	}
}

// NewGetWalletVerifyAddressAddrParamsWithContext creates a new GetWalletVerifyAddressAddrParams object
// with the ability to set a context for a request.
func NewGetWalletVerifyAddressAddrParamsWithContext(ctx context.Context) *GetWalletVerifyAddressAddrParams {
	return &GetWalletVerifyAddressAddrParams{
		Context: ctx,
	}
}

// NewGetWalletVerifyAddressAddrParamsWithHTTPClient creates a new GetWalletVerifyAddressAddrParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetWalletVerifyAddressAddrParamsWithHTTPClient(client *http.Client) *GetWalletVerifyAddressAddrParams {
	return &GetWalletVerifyAddressAddrParams{
		HTTPClient: client,
	}
}

/* GetWalletVerifyAddressAddrParams contains all the parameters to send to the API endpoint
   for the get wallet verify address addr operation.

   Typically these are written to a http.Request.
*/
type GetWalletVerifyAddressAddrParams struct {

	// Addr.
	Addr string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get wallet verify address addr params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetWalletVerifyAddressAddrParams) WithDefaults() *GetWalletVerifyAddressAddrParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get wallet verify address addr params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetWalletVerifyAddressAddrParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get wallet verify address addr params
func (o *GetWalletVerifyAddressAddrParams) WithTimeout(timeout time.Duration) *GetWalletVerifyAddressAddrParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get wallet verify address addr params
func (o *GetWalletVerifyAddressAddrParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get wallet verify address addr params
func (o *GetWalletVerifyAddressAddrParams) WithContext(ctx context.Context) *GetWalletVerifyAddressAddrParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get wallet verify address addr params
func (o *GetWalletVerifyAddressAddrParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get wallet verify address addr params
func (o *GetWalletVerifyAddressAddrParams) WithHTTPClient(client *http.Client) *GetWalletVerifyAddressAddrParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get wallet verify address addr params
func (o *GetWalletVerifyAddressAddrParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAddr adds the addr to the get wallet verify address addr params
func (o *GetWalletVerifyAddressAddrParams) WithAddr(addr string) *GetWalletVerifyAddressAddrParams {
	o.SetAddr(addr)
	return o
}

// SetAddr adds the addr to the get wallet verify address addr params
func (o *GetWalletVerifyAddressAddrParams) SetAddr(addr string) {
	o.Addr = addr
}

// WriteToRequest writes these params to a swagger request
func (o *GetWalletVerifyAddressAddrParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param addr
	if err := r.SetPathParam("addr", o.Addr); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
