// Code generated by go-swagger; DO NOT EDIT.

package wallet

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetWalletVerifyAddressAddrParams creates a new GetWalletVerifyAddressAddrParams object
// with the default values initialized.
func NewGetWalletVerifyAddressAddrParams() *GetWalletVerifyAddressAddrParams {
	var ()
	return &GetWalletVerifyAddressAddrParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetWalletVerifyAddressAddrParamsWithTimeout creates a new GetWalletVerifyAddressAddrParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetWalletVerifyAddressAddrParamsWithTimeout(timeout time.Duration) *GetWalletVerifyAddressAddrParams {
	var ()
	return &GetWalletVerifyAddressAddrParams{

		timeout: timeout,
	}
}

// NewGetWalletVerifyAddressAddrParamsWithContext creates a new GetWalletVerifyAddressAddrParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetWalletVerifyAddressAddrParamsWithContext(ctx context.Context) *GetWalletVerifyAddressAddrParams {
	var ()
	return &GetWalletVerifyAddressAddrParams{

		Context: ctx,
	}
}

// NewGetWalletVerifyAddressAddrParamsWithHTTPClient creates a new GetWalletVerifyAddressAddrParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetWalletVerifyAddressAddrParamsWithHTTPClient(client *http.Client) *GetWalletVerifyAddressAddrParams {
	var ()
	return &GetWalletVerifyAddressAddrParams{
		HTTPClient: client,
	}
}

/*GetWalletVerifyAddressAddrParams contains all the parameters to send to the API endpoint
for the get wallet verify address addr operation typically these are written to a http.Request
*/
type GetWalletVerifyAddressAddrParams struct {

	/*Addr*/
	Addr string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get wallet verify address addr params
func (o *GetWalletVerifyAddressAddrParams) WithTimeout(timeout time.Duration) *GetWalletVerifyAddressAddrParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get wallet verify address addr params
func (o *GetWalletVerifyAddressAddrParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get wallet verify address addr params
func (o *GetWalletVerifyAddressAddrParams) WithContext(ctx context.Context) *GetWalletVerifyAddressAddrParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get wallet verify address addr params
func (o *GetWalletVerifyAddressAddrParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get wallet verify address addr params
func (o *GetWalletVerifyAddressAddrParams) WithHTTPClient(client *http.Client) *GetWalletVerifyAddressAddrParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get wallet verify address addr params
func (o *GetWalletVerifyAddressAddrParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAddr adds the addr to the get wallet verify address addr params
func (o *GetWalletVerifyAddressAddrParams) WithAddr(addr string) *GetWalletVerifyAddressAddrParams {
	o.SetAddr(addr)
	return o
}

// SetAddr adds the addr to the get wallet verify address addr params
func (o *GetWalletVerifyAddressAddrParams) SetAddr(addr string) {
	o.Addr = addr
}

// WriteToRequest writes these params to a swagger request
func (o *GetWalletVerifyAddressAddrParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param addr
	if err := r.SetPathParam("addr", o.Addr); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
