// Code generated by go-swagger; DO NOT EDIT.

package wallet

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPostWalletLockParams creates a new PostWalletLockParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostWalletLockParams() *PostWalletLockParams {
	return &PostWalletLockParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostWalletLockParamsWithTimeout creates a new PostWalletLockParams object
// with the ability to set a timeout on a request.
func NewPostWalletLockParamsWithTimeout(timeout time.Duration) *PostWalletLockParams {
	return &PostWalletLockParams{
		timeout: timeout,
	}
}

// NewPostWalletLockParamsWithContext creates a new PostWalletLockParams object
// with the ability to set a context for a request.
func NewPostWalletLockParamsWithContext(ctx context.Context) *PostWalletLockParams {
	return &PostWalletLockParams{
		Context: ctx,
	}
}

// NewPostWalletLockParamsWithHTTPClient creates a new PostWalletLockParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostWalletLockParamsWithHTTPClient(client *http.Client) *PostWalletLockParams {
	return &PostWalletLockParams{
		HTTPClient: client,
	}
}

/* PostWalletLockParams contains all the parameters to send to the API endpoint
   for the post wallet lock operation.

   Typically these are written to a http.Request.
*/
type PostWalletLockParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post wallet lock params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostWalletLockParams) WithDefaults() *PostWalletLockParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post wallet lock params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostWalletLockParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post wallet lock params
func (o *PostWalletLockParams) WithTimeout(timeout time.Duration) *PostWalletLockParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post wallet lock params
func (o *PostWalletLockParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post wallet lock params
func (o *PostWalletLockParams) WithContext(ctx context.Context) *PostWalletLockParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post wallet lock params
func (o *PostWalletLockParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post wallet lock params
func (o *PostWalletLockParams) WithHTTPClient(client *http.Client) *PostWalletLockParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post wallet lock params
func (o *PostWalletLockParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *PostWalletLockParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
