// Code generated by go-swagger; DO NOT EDIT.

package wallet

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPostWalletUnlockParams creates a new PostWalletUnlockParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostWalletUnlockParams() *PostWalletUnlockParams {
	return &PostWalletUnlockParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostWalletUnlockParamsWithTimeout creates a new PostWalletUnlockParams object
// with the ability to set a timeout on a request.
func NewPostWalletUnlockParamsWithTimeout(timeout time.Duration) *PostWalletUnlockParams {
	return &PostWalletUnlockParams{
		timeout: timeout,
	}
}

// NewPostWalletUnlockParamsWithContext creates a new PostWalletUnlockParams object
// with the ability to set a context for a request.
func NewPostWalletUnlockParamsWithContext(ctx context.Context) *PostWalletUnlockParams {
	return &PostWalletUnlockParams{
		Context: ctx,
	}
}

// NewPostWalletUnlockParamsWithHTTPClient creates a new PostWalletUnlockParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostWalletUnlockParamsWithHTTPClient(client *http.Client) *PostWalletUnlockParams {
	return &PostWalletUnlockParams{
		HTTPClient: client,
	}
}

/* PostWalletUnlockParams contains all the parameters to send to the API endpoint
   for the post wallet unlock operation.

   Typically these are written to a http.Request.
*/
type PostWalletUnlockParams struct {

	/* Encryptionpassword.

	   Password that gets used to decrypt the file. Most frequently, the encryption password is the same as the primary wallet seed.
	*/
	Encryptionpassword *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post wallet unlock params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostWalletUnlockParams) WithDefaults() *PostWalletUnlockParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post wallet unlock params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostWalletUnlockParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post wallet unlock params
func (o *PostWalletUnlockParams) WithTimeout(timeout time.Duration) *PostWalletUnlockParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post wallet unlock params
func (o *PostWalletUnlockParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post wallet unlock params
func (o *PostWalletUnlockParams) WithContext(ctx context.Context) *PostWalletUnlockParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post wallet unlock params
func (o *PostWalletUnlockParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post wallet unlock params
func (o *PostWalletUnlockParams) WithHTTPClient(client *http.Client) *PostWalletUnlockParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post wallet unlock params
func (o *PostWalletUnlockParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithEncryptionpassword adds the encryptionpassword to the post wallet unlock params
func (o *PostWalletUnlockParams) WithEncryptionpassword(encryptionpassword *string) *PostWalletUnlockParams {
	o.SetEncryptionpassword(encryptionpassword)
	return o
}

// SetEncryptionpassword adds the encryptionpassword to the post wallet unlock params
func (o *PostWalletUnlockParams) SetEncryptionpassword(encryptionpassword *string) {
	o.Encryptionpassword = encryptionpassword
}

// WriteToRequest writes these params to a swagger request
func (o *PostWalletUnlockParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Encryptionpassword != nil {

		// query param encryptionpassword
		var qrEncryptionpassword string

		if o.Encryptionpassword != nil {
			qrEncryptionpassword = *o.Encryptionpassword
		}
		qEncryptionpassword := qrEncryptionpassword
		if qEncryptionpassword != "" {

			if err := r.SetQueryParam("encryptionpassword", qEncryptionpassword); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
