// Code generated by go-swagger; DO NOT EDIT.

package wallet

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/jkawamoto/go-sia/models"
)

// PostWalletSiagkeyReader is a Reader for the PostWalletSiagkey structure.
type PostWalletSiagkeyReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostWalletSiagkeyReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 204:
		result := NewPostWalletSiagkeyNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewPostWalletSiagkeyDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPostWalletSiagkeyNoContent creates a PostWalletSiagkeyNoContent with default headers values
func NewPostWalletSiagkeyNoContent() *PostWalletSiagkeyNoContent {
	return &PostWalletSiagkeyNoContent{}
}

/*PostWalletSiagkeyNoContent handles this case with default header values.

Successful Response
*/
type PostWalletSiagkeyNoContent struct {
}

func (o *PostWalletSiagkeyNoContent) Error() string {
	return fmt.Sprintf("[POST /wallet/siagkey][%d] postWalletSiagkeyNoContent ", 204)
}

func (o *PostWalletSiagkeyNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostWalletSiagkeyDefault creates a PostWalletSiagkeyDefault with default headers values
func NewPostWalletSiagkeyDefault(code int) *PostWalletSiagkeyDefault {
	return &PostWalletSiagkeyDefault{
		_statusCode: code,
	}
}

/*PostWalletSiagkeyDefault handles this case with default header values.

Error Response
*/
type PostWalletSiagkeyDefault struct {
	_statusCode int

	Payload *models.StandardError
}

// Code gets the status code for the post wallet siagkey default response
func (o *PostWalletSiagkeyDefault) Code() int {
	return o._statusCode
}

func (o *PostWalletSiagkeyDefault) Error() string {
	return fmt.Sprintf("[POST /wallet/siagkey][%d] PostWalletSiagkey default  %+v", o._statusCode, o.Payload)
}

func (o *PostWalletSiagkeyDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StandardError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
