// Code generated by go-swagger; DO NOT EDIT.

package wallet

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/jkawamoto/go-sia/models"
)

// PostWalletChangepasswordReader is a Reader for the PostWalletChangepassword structure.
type PostWalletChangepasswordReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostWalletChangepasswordReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewPostWalletChangepasswordNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewPostWalletChangepasswordDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPostWalletChangepasswordNoContent creates a PostWalletChangepasswordNoContent with default headers values
func NewPostWalletChangepasswordNoContent() *PostWalletChangepasswordNoContent {
	return &PostWalletChangepasswordNoContent{}
}

/*PostWalletChangepasswordNoContent handles this case with default header values.

Successful Response
*/
type PostWalletChangepasswordNoContent struct {
}

func (o *PostWalletChangepasswordNoContent) Error() string {
	return fmt.Sprintf("[POST /wallet/changepassword][%d] postWalletChangepasswordNoContent ", 204)
}

func (o *PostWalletChangepasswordNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostWalletChangepasswordDefault creates a PostWalletChangepasswordDefault with default headers values
func NewPostWalletChangepasswordDefault(code int) *PostWalletChangepasswordDefault {
	return &PostWalletChangepasswordDefault{
		_statusCode: code,
	}
}

/*PostWalletChangepasswordDefault handles this case with default header values.

Error Response
*/
type PostWalletChangepasswordDefault struct {
	_statusCode int

	Payload *models.StandardError
}

// Code gets the status code for the post wallet changepassword default response
func (o *PostWalletChangepasswordDefault) Code() int {
	return o._statusCode
}

func (o *PostWalletChangepasswordDefault) Error() string {
	return fmt.Sprintf("[POST /wallet/changepassword][%d] PostWalletChangepassword default  %+v", o._statusCode, o.Payload)
}

func (o *PostWalletChangepasswordDefault) GetPayload() *models.StandardError {
	return o.Payload
}

func (o *PostWalletChangepasswordDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StandardError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
