// Code generated by go-swagger; DO NOT EDIT.

package miner

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetMinerStartParams creates a new GetMinerStartParams object
// with the default values initialized.
func NewGetMinerStartParams() *GetMinerStartParams {

	return &GetMinerStartParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetMinerStartParamsWithTimeout creates a new GetMinerStartParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetMinerStartParamsWithTimeout(timeout time.Duration) *GetMinerStartParams {

	return &GetMinerStartParams{

		timeout: timeout,
	}
}

// NewGetMinerStartParamsWithContext creates a new GetMinerStartParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetMinerStartParamsWithContext(ctx context.Context) *GetMinerStartParams {

	return &GetMinerStartParams{

		Context: ctx,
	}
}

// NewGetMinerStartParamsWithHTTPClient creates a new GetMinerStartParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetMinerStartParamsWithHTTPClient(client *http.Client) *GetMinerStartParams {

	return &GetMinerStartParams{
		HTTPClient: client,
	}
}

/*GetMinerStartParams contains all the parameters to send to the API endpoint
for the get miner start operation typically these are written to a http.Request
*/
type GetMinerStartParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get miner start params
func (o *GetMinerStartParams) WithTimeout(timeout time.Duration) *GetMinerStartParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get miner start params
func (o *GetMinerStartParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get miner start params
func (o *GetMinerStartParams) WithContext(ctx context.Context) *GetMinerStartParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get miner start params
func (o *GetMinerStartParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get miner start params
func (o *GetMinerStartParams) WithHTTPClient(client *http.Client) *GetMinerStartParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get miner start params
func (o *GetMinerStartParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetMinerStartParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
