// Code generated by go-swagger; DO NOT EDIT.

package miner

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetMinerStopParams creates a new GetMinerStopParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetMinerStopParams() *GetMinerStopParams {
	return &GetMinerStopParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetMinerStopParamsWithTimeout creates a new GetMinerStopParams object
// with the ability to set a timeout on a request.
func NewGetMinerStopParamsWithTimeout(timeout time.Duration) *GetMinerStopParams {
	return &GetMinerStopParams{
		timeout: timeout,
	}
}

// NewGetMinerStopParamsWithContext creates a new GetMinerStopParams object
// with the ability to set a context for a request.
func NewGetMinerStopParamsWithContext(ctx context.Context) *GetMinerStopParams {
	return &GetMinerStopParams{
		Context: ctx,
	}
}

// NewGetMinerStopParamsWithHTTPClient creates a new GetMinerStopParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetMinerStopParamsWithHTTPClient(client *http.Client) *GetMinerStopParams {
	return &GetMinerStopParams{
		HTTPClient: client,
	}
}

/* GetMinerStopParams contains all the parameters to send to the API endpoint
   for the get miner stop operation.

   Typically these are written to a http.Request.
*/
type GetMinerStopParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get miner stop params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetMinerStopParams) WithDefaults() *GetMinerStopParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get miner stop params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetMinerStopParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get miner stop params
func (o *GetMinerStopParams) WithTimeout(timeout time.Duration) *GetMinerStopParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get miner stop params
func (o *GetMinerStopParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get miner stop params
func (o *GetMinerStopParams) WithContext(ctx context.Context) *GetMinerStopParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get miner stop params
func (o *GetMinerStopParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get miner stop params
func (o *GetMinerStopParams) WithHTTPClient(client *http.Client) *GetMinerStopParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get miner stop params
func (o *GetMinerStopParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetMinerStopParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
