// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
)

// TransactionSet transaction set
// swagger:model TransactionSet
type TransactionSet []string

// Validate validates this transaction set
func (m TransactionSet) Validate(formats strfmt.Registry) error {
	return nil
}
